---
title: "ACM Preliminary Analysis"
author: "Mihai Sirbu"
date: "Wednesday, May 06, 2015"
output: html_document
---

```{r, echo=FALSE, include=FALSE}
library(dplyr)
```

###Read in Data

```{r}
data = as.tbl(read.csv("student-por.csv", sep=";", stringsAsFactors=TRUE))
```

###Rename the Variables

```{r}

rename_cols <- c(4:12,16:21,23:24,26:28,31:33)

colnames(data)[rename_cols] = c("urban_rural",
                                "fam_size",
                                "parents_cohabit",
                                "mom_edu",
                                "dad_edu",
                                "mom_job",
                                "dad_job",
                                "school_reason",
                                "student_guardian",
                                "extra_school_support",
                                "fam_edu_support",
                                "paid_extra_classes",
                                "extracurricular_activities",
                                "attended_nursery",
                                "wants_higher_education",
                                "has_romantic_partner",
                                "family_relationship",
                                "going_out_amount",
                                "weekday_alcohol_cons",
                                "weekend_alcohol_cons",
                                "grade_one",
                                "grade_two",
                                "final_grade")
```

###Meaningful Variable Values

```{r}
data <-  data %>% 
  mutate(school = ifelse(school=='GP', 'Gabriel Pereira', 'Mousinho da Silveira')) %>%
  mutate(urban_rural = ifelse(urban_rural=='R', 'Rural', 'Urban')) %>% 
  mutate(fam_size = ifelse(fam_size=='GT3', '>3', '<=3')) %>%
  mutate(parents_cohabit = ifelse(parents_cohabit=='A', 'Apart', 'Together')) %>%
  mutate_each_(funs(ifelse(.=='yes', TRUE, FALSE)), 
               c("extra_school_support", "fam_edu_support", "paid_extra_classes", 
                 "extracurricular_activities", "attended_nursery", 
                 "wants_higher_education", "internet", "has_romantic_partner"))
  
```

###Regression Using Sex as a Variable

```{r}
lm_sex <- lm(final_grade ~ sex, data = data)

summary(lm_sex)

```

The average grade for females  is 12.25 whereas the average grade for Males is 11.40. The difference between the two is signifcant (p < 0.001); the R-squared is 0.015.
