---
title: "ACM_Final_Proj"
author: "Alyster Alcudia, Cynthia Gan, Mihai Sirbu"
date: "5/2/2015"
output: pdf_document
---

```{r, echo=FALSE, include=FALSE}
install.packages("corrplot")
install.packages("dplyr")

library(corrplot)
library(dplyr)
```

```{r}
data = as.tbl(read.csv("student-por.csv", sep=";", stringsAsFactors = TRUE))
```

Let's rename the variables better!
```{r}

rename_cols <- c(6, 11:12,16:21,23:24,26:28)

colnames(data)[rename_cols] = c("parents_cohabit",
                                "school_reason",
                                "student_guardian",
                                "extra_school_support",
                                "fam_edu_support",
                                "paid_extra_classes",
                                "extracurricular activites",
                                "attended_nursery",
                                "wants_higher_education",
                                "has_romantic_partner",
                                "family_relationship",
                                "going_out_amount",
                                "Weekday_Alcohol_Cons",
                                "Weekend_Alcohol_Cons")

```
Basic view of the data
```{r}
dim(data)
summary(data)
```

Correlation betweens between different grades and
numeric variables
```{r}
data %>%
  select(one_of("age","failures","family_relationship",
                "freetime","going_out_amount",
                "Weekday_Alcohol_Cons",
                "Weekend_Alcohol_Cons","absences",
                "G1","G2","G3")) %>%
  cor() %>%
  corrplot(method="circle",type="upper")

```