---
title: "ACM Final Report"
author: "Alyster Alcudia, Cynthia Gan, Mihai Sirbu"
date: "Monday, May 18, 2015"
output: pdf_document
---

```{r, echo=FALSE, include=FALSE}
for(i in c("dplyr", "MASS")){
    if( ! require( i , character.only = TRUE ) ){
      #  If package was not able to be loaded then re-install
      install.packages( i , dependencies = TRUE )
      library( i , character.only = TRUE )
    }
}
```

#Summary

1) Describe the task you performed (in one sentence). 
2) Describe the data you used (in one sentence). 
3) Describe the analysis method you used (in one sentence). 
4) Summarize your results (in one or two sentences).

#Introduction

(1/2 page): Describe the task you performed in more detail. Include motivation for performing this task.

#Materials and Methods

(1.5-2 pages): Describe the dataset you used in more detail (you can get this from Step 3) Describe analysis methods you used, and how you are evaluating performance (from Step 3)

#Results

Describe the results you found. Make sure you quantify your findings (if inference, provide interpretation of resulting model. E.g., we found that house prices increase by $10,000 (P<0.05) on average when they are within 5 miles of a university campus; if prediction, we found we could predict house prices with mean squared error of $10,000.

#Conclusion

(1/2 page): Concluding remarks summarizing findings and discussing possible improvements to your analysis.